# frozen_string_literal: true

module Coradoc
  # CoreModel namespace for format-agnostic document models
  #
  # CoreModel provides the canonical document representation used as the hub
  # in the hub-and-spoke architecture. Format-specific builders live in their
  # respective format gems (e.g., Coradoc::AsciiDoc::Builder).
  #
  # @see CoreModel::Base for base functionality
  module CoreModel
    # Autoload submodules lazily using relative paths
    autoload :Base, "#{__dir__}/core_model/base"
    autoload :ChildrenContent, "#{__dir__}/core_model/children_content"
    autoload :HasChildren, "#{__dir__}/core_model/has_children"
    autoload :Callout, "#{__dir__}/core_model/callout"
    autoload :CalloutText, "#{__dir__}/core_model/callout_text"
    autoload :Block, "#{__dir__}/core_model/block"
    autoload :AnnotationBlock, "#{__dir__}/core_model/annotation_block"
    autoload :ListBlock, "#{__dir__}/core_model/list_block"
    autoload :ListItem, "#{__dir__}/core_model/list_item"
    autoload :InlineElement, "#{__dir__}/core_model/inline_element"
    autoload :BoldElement, "#{__dir__}/core_model/inline_element"
    autoload :ItalicElement, "#{__dir__}/core_model/inline_element"
    autoload :MonospaceElement, "#{__dir__}/core_model/inline_element"
    autoload :UnderlineElement, "#{__dir__}/core_model/inline_element"
    autoload :StrikethroughElement, "#{__dir__}/core_model/inline_element"
    autoload :SubscriptElement, "#{__dir__}/core_model/inline_element"
    autoload :SuperscriptElement, "#{__dir__}/core_model/inline_element"
    autoload :HighlightElement, "#{__dir__}/core_model/inline_element"
    autoload :LinkElement, "#{__dir__}/core_model/inline_element"
    autoload :CrossReferenceElement, "#{__dir__}/core_model/inline_element"
    autoload :StemElement, "#{__dir__}/core_model/inline_element"
    autoload :FootnoteElement, "#{__dir__}/core_model/inline_element"
    autoload :HardLineBreakElement, "#{__dir__}/core_model/inline_element"
    autoload :TextElement, "#{__dir__}/core_model/inline_element"
    autoload :SpanElement, "#{__dir__}/core_model/inline_element"
    autoload :TermElement, "#{__dir__}/core_model/inline_element"
    autoload :LineBreakElement, "#{__dir__}/core_model/inline_element"
    autoload :RawInlineElement, "#{__dir__}/core_model/raw_inline_element"
    autoload :StructuralElement, "#{__dir__}/core_model/structural_element"
    autoload :DocumentElement, "#{__dir__}/core_model/structural_element"
    autoload :SectionElement, "#{__dir__}/core_model/structural_element"
    autoload :PreambleElement, "#{__dir__}/core_model/structural_element"
    autoload :HeaderElement, "#{__dir__}/core_model/structural_element"

    autoload :Table, "#{__dir__}/core_model/table"
    autoload :TableCell, "#{__dir__}/core_model/table"
    autoload :TableRow, "#{__dir__}/core_model/table"
    autoload :TextContent, "#{__dir__}/core_model/text_content"
    autoload :Image, "#{__dir__}/core_model/image"
    autoload :Term, "#{__dir__}/core_model/term"
    autoload :ElementAttribute, "#{__dir__}/core_model/element_attribute"
    autoload :Metadata, "#{__dir__}/core_model/metadata"
    autoload :MetadataEntry, "#{__dir__}/core_model/metadata"
    autoload :FrontmatterBlock, "#{__dir__}/core_model/frontmatter"
    autoload :Footnote, "#{__dir__}/core_model/footnote"
    autoload :FootnoteReference, "#{__dir__}/core_model/footnote"
    autoload :Abbreviation, "#{__dir__}/core_model/footnote"
    autoload :DefinitionItem, "#{__dir__}/core_model/definition_item"
    autoload :DefinitionList, "#{__dir__}/core_model/definition_list"
    autoload :Toc, "#{__dir__}/core_model/toc"
    autoload :TocEntry, "#{__dir__}/core_model/toc"
    autoload :TocGenerator, "#{__dir__}/core_model/toc_generator"
    autoload :Bibliography, "#{__dir__}/core_model/bibliography"
    autoload :BibliographyEntry, "#{__dir__}/core_model/bibliography_entry"
    autoload :SourceBlock, "#{__dir__}/core_model/source_block"
    autoload :ExampleBlock, "#{__dir__}/core_model/example_block"
    autoload :QuoteBlock, "#{__dir__}/core_model/quote_block"
    autoload :SidebarBlock, "#{__dir__}/core_model/sidebar_block"
    autoload :LiteralBlock, "#{__dir__}/core_model/literal_block"
    autoload :PassBlock, "#{__dir__}/core_model/pass_block"
    autoload :ListingBlock, "#{__dir__}/core_model/listing_block"
    autoload :OpenBlock, "#{__dir__}/core_model/open_block"
    autoload :VerseBlock, "#{__dir__}/core_model/verse_block"
    autoload :ReviewerBlock, "#{__dir__}/core_model/reviewer_block"
    autoload :ParagraphBlock, "#{__dir__}/core_model/paragraph_block"
    autoload :CommentBlock, "#{__dir__}/core_model/comment_block"
    autoload :CommentLine, "#{__dir__}/core_model/comment_line"
    autoload :HorizontalRuleBlock, "#{__dir__}/core_model/horizontal_rule_block"
    autoload :IdGenerator, "#{__dir__}/core_model/id_generator"
    autoload :Include, "#{__dir__}/core_model/include"
    autoload :IncludeOptions, "#{__dir__}/core_model/include_options"
    autoload :IncludeLevelOffset, "#{__dir__}/core_model/include_level_offset"
  end
end
