#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require 'coradoc'
require 'coradoc/cli'

GEM_TO_REQUIRE_PATH = {
  'coradoc-adoc' => 'coradoc/asciidoc',
  'coradoc-html' => 'coradoc/html',
  'coradoc-markdown' => 'coradoc/markdown',
  'coradoc-docx' => 'coradoc/docx'
}.freeze

GEM_TO_REQUIRE_PATH.each do |gem_name, require_path|
  begin
    gem gem_name
    require require_path
  rescue LoadError
    nil
  end
end

Coradoc::CLI.start(ARGV)
