AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 25

Layout/LineLength:
  Max: 120
