# frozen_string_literal: true

source 'https://rubygems.org'

# Jekyll and theme
gem 'jekyll', '~> 4.3'
gem 'just-the-docs', '~> 0.8'

# Syntax highlighting (GitHub Pages compatible)
gem 'rouge', '~> 4.2'

group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end

# Development (for local testing and link validation)
group :development do
  gem 'html-proofer', '~> 5.0'
end
