name: rake

on:
  push:
    branches: [master, main]
    tags: [v*]
  pull_request:

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/monorepo-rake.yml@monorepo-workflows
    with:
      spec-dirs: >-
        ["spec","coradoc-adoc/spec","coradoc-html/spec","coradoc-markdown/spec"]
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
