name: release

on:
  workflow_dispatch:
    inputs:
      gem_name:
        description: Select gem to release
        required: true
        type: choice
        options:
          - coradoc
          - coradoc-adoc
          - coradoc-html
          - coradoc-markdown
          - coradoc-docx
      next_version:
        description: >-
          Next release version. Possible values: x.y.z, major, minor,
          patch (or pre|rc|etc).  Pass 'skip' to skip 'git tag' and do
          'gem push' for the current version.
        required: true
        default: skip
  repository_dispatch:
    types: [do-release]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    uses: metanorma/ci/.github/workflows/monorepo-rubygems-release.yml@monorepo-workflows
    with:
      gem_name: ${{ github.event.inputs.gem_name || 'coradoc' }}
      gem_directory: .
      next_version: ${{ github.event.inputs.next_version || 'skip' }}
    secrets:
      rubygems-api-key: ${{ secrets.METANORMA_CI_RUBYGEMS_API_KEY }}
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
